name: Deploy to Firebase

on:
  push:
    branches: [master]

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: npm ci
    - run: npm run build -- --prod --vendor-chunk=true
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
